C Copyright (c) 1980, InfoCom Computers and Communications, Cambridge MA 02142
C All rights reserved, commercial usage strictly prohibited.
C Written by R. M. Supnik.
C Revisions Copyright (c) 2021, Darth Spectra (Lydia Marie Williamson).
C
        SUBROUTINE INTIME(HOURS, MINUTES, SECONDS)
	IMPLICIT INTEGER (A-Z)
        DIMENSION TARRAY(3)
C	CALL GETTIM(HOURS, MINUTES, SECONDS, HUNDREDTHS)
        CALL ITIME(TARRAY)
        HOURS = TARRAY(1)
        MINUTES = TARRAY(2)
        SECONDS = TARRAY(3)
	END

	SUBROUTINE INIRND(SEED)
	INTEGER SEED,SEEDY
	COMMON /RANDOM/ SEEDY
	SEEDY = SEED
	END

	FUNCTION RND(MAXVAL)
	IMPLICIT INTEGER (A-Z)
	COMMON /RANDOM/ SEEDY
	SEEDY = IAND(SEEDY*(1024+32+2+1) + 17, Z'7FFFFFFF')
	RND = MOD((SEEDY/100),MAXVAL)
	END

	SUBROUTINE EXIT
C NO "CALL EXIT" HERE
	STOP
	END

