C Vocabularies
	COMMON /BUZVOC/ BVOC(20)
	COMMON /PRPVOC/ PVOC(45)
	COMMON /DIRVOC/ DVOC(75)
C Was: INTEGER AVOC(450) split/equivalenced into COMMON BLOCK /ADJVOC/
	COMMON /ADJVOC/ AVOC(405)
C Was: INTEGER VVOC(950) split/equivalenced into COMMON BLOCK /VRBVOC/
	COMMON /VRBVOC/ VVOC(935)
C Was: INTEGER OVOC(1050) split/equivalenced into COMMON BLOCK /OBJVOC/
	COMMON /OBJVOC/ OVOC(1022)
